#!/bin/bash

cat <<MIME
Content-Type: text/plain
Access-Control-Allow-Origin: *

MIME

[[ $QUERY_STRING == '' ]] && echo no query && exit

db=weights.csv

echo -e "$(date +%Y/%m/%d),\t$QUERY_STRING\n$(cat $db)" > $db

cat '<pre>' $db '</pre>'

# height=182
# echo $(( (753 / ((182 * 182) / (100 * 100))) / 10 ))
