#!/bin/bash

# Check params
[[ $# < 1 ]] && echo Error: no query && exit

readonly mass=$1

# Optional heartrate
[[ $# == 2 ]] && readonly heartrate=$2

# Database
db=weights.csv

# Today's date
date=$(date +%Y/%m/%d)

# Check if we've already submitted one today
if [[ $(grep $date $db) ]]; then

	echo Error: already submitted today
else

	echo -e "$date,\t$mass,\t$heartrate" >> $db
	cat $db

	# Print stats
	runhaskell bmi.hs $mass

	git commit -am daily
	git push
fi
